### ISSUE TITLE
Licensing Information?

### ISSUE THREAD

**Issue by howardroark2018** [chrisle/seer.js#3]
Hello sir! I was wondering , under what license is this code available. A bit of googling pointed me towards a probable MIT license, But I couldn't find any official claim regarding this. 
It's surely an awesome project directed towards common people with its approach of simplicity and complete lack of complexity. Keep it up, boss! Cheers!! 

Anime.sh

**Comment by howardroark2018** [comment]
Hello everyone! 
I am eagerly waiting for a reply. And , If anyone knows even a bit about this issue , then I request 'em to please share it with the community by posting a comment here.

Thanks!

**Comment by howardroark2018** [comment]
:( :(

**Comment by howardroark2018** [comment]
Is this project dead, already??

**Comment by smhmic** [comment]
You are correct, this is under the MIT license.  https://github.com/chrisle/seer.js/blob/master/build/seer.min.js

**Comment by howardroark2018** [comment]
Thanks a lot for the reply!  Again, the projects just awesome, and the license has made my day! :D
